version: '3'
services:
  external-api:
    image: node:16.14.2-alpine3.14
    command: sh -c 'yarn install && exec node main.js'
    ports:
      - 3000:3000
    volumes:
      - ./dependencies/external-api/:/opt/external-api/
    working_dir: /opt/external-api/

  mysql:
    image: mysql:8.0.28
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./dependencies/mysql/sqls/:/sqls/
